# Generated by Django 5.0.6 on 2024-06-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body_text_alter_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
