# Generated by Django 5.0.6 on 2024-06-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_date_comment_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body_text',
        ),
    ]
